/**
 *
 * $Id$
 */
package geometry.validation;

import geometry.ShapeChangeEventType;

/**
 * A sample validator interface for {@link geometry.ShapeChangeEvent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ShapeChangeEventValidator {
	boolean validate();

	boolean validateType(ShapeChangeEventType value);
	boolean validateValue(String value);
}
