/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.eavp.sTL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.eavp.sTL.Model#getName <em>Name</em>}</li>
 *   <li>{@link org.eclipse.eavp.sTL.Model#getTriangles <em>Triangles</em>}</li>
 * </ul>
 *
 * @see org.eclipse.eavp.sTL.STLPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.eclipse.eavp.sTL.STLPackage#getModel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.eclipse.eavp.sTL.Model#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Triangles</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.eavp.sTL.Triangle}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Triangles</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Triangles</em>' containment reference list.
   * @see org.eclipse.eavp.sTL.STLPackage#getModel_Triangles()
   * @model containment="true"
   * @generated
   */
  EList<Triangle> getTriangles();

} // Model
