/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.eavp.sTL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Normal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.eavp.sTL.Normal#getVector <em>Vector</em>}</li>
 * </ul>
 *
 * @see org.eclipse.eavp.sTL.STLPackage#getNormal()
 * @model
 * @generated
 */
public interface Normal extends EObject
{
  /**
   * Returns the value of the '<em><b>Vector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vector</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vector</em>' containment reference.
   * @see #setVector(Vector)
   * @see org.eclipse.eavp.sTL.STLPackage#getNormal_Vector()
   * @model containment="true"
   * @generated
   */
  Vector getVector();

  /**
   * Sets the value of the '{@link org.eclipse.eavp.sTL.Normal#getVector <em>Vector</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Vector</em>' containment reference.
   * @see #getVector()
   * @generated
   */
  void setVector(Vector value);

} // Normal
