/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.eavp.sTL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verticies</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.eclipse.eavp.sTL.Verticies#getV1 <em>V1</em>}</li>
 *   <li>{@link org.eclipse.eavp.sTL.Verticies#getV2 <em>V2</em>}</li>
 *   <li>{@link org.eclipse.eavp.sTL.Verticies#getV3 <em>V3</em>}</li>
 * </ul>
 *
 * @see org.eclipse.eavp.sTL.STLPackage#getVerticies()
 * @model
 * @generated
 */
public interface Verticies extends EObject
{
  /**
   * Returns the value of the '<em><b>V1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>V1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>V1</em>' containment reference.
   * @see #setV1(Vertex)
   * @see org.eclipse.eavp.sTL.STLPackage#getVerticies_V1()
   * @model containment="true"
   * @generated
   */
  Vertex getV1();

  /**
   * Sets the value of the '{@link org.eclipse.eavp.sTL.Verticies#getV1 <em>V1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V1</em>' containment reference.
   * @see #getV1()
   * @generated
   */
  void setV1(Vertex value);

  /**
   * Returns the value of the '<em><b>V2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>V2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>V2</em>' containment reference.
   * @see #setV2(Vertex)
   * @see org.eclipse.eavp.sTL.STLPackage#getVerticies_V2()
   * @model containment="true"
   * @generated
   */
  Vertex getV2();

  /**
   * Sets the value of the '{@link org.eclipse.eavp.sTL.Verticies#getV2 <em>V2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V2</em>' containment reference.
   * @see #getV2()
   * @generated
   */
  void setV2(Vertex value);

  /**
   * Returns the value of the '<em><b>V3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>V3</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>V3</em>' containment reference.
   * @see #setV3(Vertex)
   * @see org.eclipse.eavp.sTL.STLPackage#getVerticies_V3()
   * @model containment="true"
   * @generated
   */
  Vertex getV3();

  /**
   * Sets the value of the '{@link org.eclipse.eavp.sTL.Verticies#getV3 <em>V3</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>V3</em>' containment reference.
   * @see #getV3()
   * @generated
   */
  void setV3(Vertex value);

} // Verticies
