/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.january.model.xtext.tests

import com.google.inject.Inject
import geometry.Geometry
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(STLInjectorProvider)
class STLParsingTest{

	@Inject
	ParseHelper<Geometry> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
