/**
 *
 * $Id$
 */
package model.validation;

import geometry.INode;

import model.MeshCache;

/**
 * A sample validator interface for {@link model.RenderObject}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RenderObjectValidator {
	boolean validate();

	boolean validateMeshCache(MeshCache<Object> value);

	boolean validateMeshcache(MeshCache<?> value);
	boolean validateRender(Object value);
	boolean validateSource(INode value);
}
