/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.january.model.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractSTLScopeProvider extends DelegatingScopeProvider {
}
