/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.eavp.ui;

import org.eclipse.eavp.ui.AbstractSTLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class STLUiModule extends AbstractSTLUiModule {
  public STLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
