/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.xtext;

import org.eclipse.january.geometry.xtext.AbstractIGESRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class IGESRuntimeModule extends AbstractIGESRuntimeModule {
}
