/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.xtext.ui.contentassist;

import org.eclipse.january.geometry.xtext.ui.contentassist.AbstractIGESProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class IGESProposalProvider extends AbstractIGESProposalProvider {
}
