/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.eavp.ui;

import com.google.inject.Injector;
import org.eclipse.eavp.stl.ui.internal.StlActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class STLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return StlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return StlActivator.getInstance().getInjector(StlActivator.ORG_ECLIPSE_EAVP_STL);
	}
	
}
