/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.eavp.validation;

import org.eclipse.eavp.validation.AbstractSTLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class STLValidator extends AbstractSTLValidator {
}
