/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.xtext.ui;

import org.eclipse.january.geometry.xtext.ui.AbstractIGESUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class IGESUiModule extends AbstractIGESUiModule {
  public IGESUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
