/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.xtext.ui;

import com.google.inject.Binder;
import com.google.inject.binder.AnnotatedBindingBuilder;
import com.google.inject.binder.LinkedBindingBuilder;
import com.google.inject.name.Named;
import com.google.inject.name.Names;
import org.eclipse.january.geometry.xtext.CustomIGESLexer;
import org.eclipse.january.geometry.xtext.ui.AbstractIGESUiModule;
import org.eclipse.january.geometry.xtext.ui.IGESAntlrTokenToAttributeIdMapper;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ide.LexerIdeBindings;
import org.eclipse.xtext.parser.antlr.Lexer;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class IGESUiModule extends AbstractIGESUiModule {
  public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
    return IGESAntlrTokenToAttributeIdMapper.class;
  }
  
  @Override
  public void configureHighlightingLexer(final Binder binder) {
    AnnotatedBindingBuilder<Lexer> _bind = binder.<Lexer>bind(Lexer.class);
    Named _named = Names.named(LexerIdeBindings.HIGHLIGHTING);
    LinkedBindingBuilder<Lexer> _annotatedWith = _bind.annotatedWith(_named);
    _annotatedWith.to(CustomIGESLexer.class);
  }
  
  public IGESUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
