/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.xtext.ui;

import com.google.inject.Binder;
import org.eclipse.january.geometry.xtext.ui.AbstractIGESUiModule;
import org.eclipse.january.geometry.xtext.ui.IGESAntlrTokenToAttributeIdMapper;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.eclipse.xtext.ui.editor.syntaxcoloring.AbstractAntlrTokenToAttributeIdMapper;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class IGESUiModule extends AbstractIGESUiModule {
  public Class<? extends AbstractAntlrTokenToAttributeIdMapper> bindAbstractAntlrTokenToAttributeIdMapper() {
    return IGESAntlrTokenToAttributeIdMapper.class;
  }
  
  @Override
  public void configureHighlightingLexer(final Binder binder) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field LexerIdeBindings is undefined"
      + "\nHIGHLIGHTING cannot be resolved");
  }
  
  public IGESUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
