/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.january.geometry.xtext.generator;

import org.eclipse.emf.ecore.resource.Resource;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class OBJGenerator /* implements AbstractGenerator  */{
  @Override
  public void doGenerate(final Resource resource, final /* IFileSystemAccess2 */Object fsa, final /* IGeneratorContext */Object context) {
  }
}
