/**
 * generated by Xtext 2.9.1
 */
package org.eclipse.eavp;

import org.eclipse.eavp.AbstractSTLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class STLRuntimeModule extends AbstractSTLRuntimeModule {
}
