/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.eavp.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class STLUiModule extends AbstractSTLUiModule {
}
