/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.eavp


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class STLStandaloneSetup extends STLStandaloneSetupGenerated {

	def static void doSetup() {
		new STLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
