/*
 * generated by Xtext 2.9.1
 */
package org.eclipse.eavp.ui.tests;

import com.google.inject.Injector;
import org.eclipse.eavp.stl.ui.internal.StlActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class STLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return StlActivator.getInstance().getInjector("org.eclipse.eavp.STL");
	}

}
