/**
 * generated by Xtext 2.9.1
 */
package xtext;

import xtext.AbstractSTLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class STLRuntimeModule extends AbstractSTLRuntimeModule {
}
