/**
 * generated by Xtext 2.9.1
 */
package xtext;

import com.google.inject.Injector;
import geometry.GeometryPackage;
import org.eclipse.emf.ecore.EPackage;
import xtext.STLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class STLStandaloneSetup extends STLStandaloneSetupGenerated {
  public static void doSetup() {
    STLStandaloneSetup _sTLStandaloneSetup = new STLStandaloneSetup();
    _sTLStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
  
  @Override
  public void register(final Injector injector) {
    boolean _containsKey = EPackage.Registry.INSTANCE.containsKey("http://www.eclipse.org/");
    boolean _not = (!_containsKey);
    if (_not) {
      EPackage.Registry.INSTANCE.put("http://www.eclipse.org/", GeometryPackage.eINSTANCE);
    }
    super.register(injector);
  }
}
